name: Show PR Changed Files

on:
  pull_request:

jobs:
  list-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Checkout the pull request branch with minimal history
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Fetch minimal history for diffing
          ref: ${{ github.head_ref }}  # Check out the pull request branch

      - name: Fetch base branch
        run: git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: List changed files
        run: |
          BASE_COMMIT=$(git merge-base HEAD origin/${{ github.event.pull_request.base.ref }})
          echo "Base commit: $BASE_COMMIT"
          CHANGED_FILES=$(git diff --name-only $BASE_COMMIT HEAD)
          echo "Changed files in this PR:"
          echo "$CHANGED_FILES"
          echo "##[group]Changed files:"
          for file in $CHANGED_FILES; do
            echo "$file"
            bandit -r $file
          done
          echo "##[endgroup]"
